In [5]:
# Useful starting lines
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
%load_ext autoreload
%autoreload 2

## Load the training data into feature matrix, class labels, and event ids:

In [6]:
from proj1_helpers import *
DATA_TRAIN_PATH = '../data/train.csv' # TODO: download train data and supply path here 
y, tX, ids = load_csv_data(DATA_TRAIN_PATH)

## Do your thing crazy machine learning thing here :) ...

In [7]:
tX

array([[ 138.47 ,   51.655,   97.827, ...,    1.24 ,   -2.475,  113.497],
       [ 160.937,   68.768,  103.235, ..., -999.   , -999.   ,   46.226],
       [-999.   ,  162.172,  125.953, ..., -999.   , -999.   ,   44.251],
       ...,
       [ 105.457,   60.526,   75.839, ..., -999.   , -999.   ,   41.992],
       [  94.951,   19.362,   68.812, ..., -999.   , -999.   ,    0.   ],
       [-999.   ,   72.756,   70.831, ..., -999.   , -999.   ,    0.   ]])

In [8]:
ids

array([100000, 100001, 100002, ..., 349997, 349998, 349999])

In [9]:
y

array([ 1., -1., -1., ...,  1., -1., -1.])

Let's try to visualize the data to get a insight about it. 

In [10]:
data = pd.DataFrame(tX);

In [23]:
data[0]

0         138.470
1         160.937
2        -999.000
3         143.905
4         175.864
5          89.744
6         148.754
7         154.916
8         105.594
9         128.053
10       -999.000
11        114.744
12        145.297
13         82.488
14       -999.000
15        111.026
16        114.256
17        127.861
18       -999.000
19       -999.000
20       -999.000
21         90.736
22         87.075
23        141.481
24        110.785
25         76.883
26        137.197
27        111.271
28        118.104
29         98.761
           ...   
249970    158.674
249971   -999.000
249972    102.569
249973    103.483
249974    128.898
249975    140.352
249976    137.371
249977     96.952
249978     86.190
249979     92.645
249980    119.934
249981     87.390
249982    146.903
249983     80.388
249984    112.308
249985    126.151
249986    164.310
249987    140.080
249988     89.509
249989   -999.000
249990    127.822
249991    133.457
249992   -999.000
249993    130.075
249994    

In [21]:
pd.DataFrame(tX[:, [0, 1, 2, 3, 7, 8, 9, 10]])

0        1        2        3      4       5        6      7
0       138.470   51.655   97.827   27.980  3.064  41.928  197.760  1.582
1       160.937   68.768  103.235   48.146  3.473   2.078  125.157  0.879
2      -999.000  162.172  125.953   35.635  3.148   9.336  197.814  3.776
3       143.905   81.417   80.943    0.414  3.310   0.414   75.968  2.354
4       175.864   16.915  134.805   16.405  3.891  16.405   57.983  1.056
5        89.744   13.550   59.149  116.344  1.362  61.619  278.876  0.588
6       148.754   28.862  107.782  106.130  2.941   2.545  305.967  3.371
7       154.916   10.418   94.714   29.169  2.897   1.526  138.178  0.365
8       105.594   50.559  100.989    4.288  2.904   4.288   65.333  0.675
9       128.053   88.941   69.272  193.392  1.609  28.859  255.123  0.599
10     -999.000   86.240   79.692   27.201  2.338  27.201   81.734  1.750
11      114.744   10.286   75.712   30.816  2.888  36.745  239.804  1.061
12      145.297   64.234  103.565  106.999  2.183  24.660  192.245  0.576
13       82.488   31.663   64.128    8.232  2.823   8.232   58.649  1.303
14     -999.000  109.412   14.398   17.323  0.472  17.323   62.565  1.774
15      111.026   32.096   75.271   23.067  3.205  23.067   69.649  1.276
16      114.256    4.351   67.963   47.221  2.954  26.243  100.930  1.145
17      127.861   50.953   77.267   26.967  2.833  26.967   79.503  1.586
18     -999.000   85.186   68.827    5.042  2.116   5.042   71.443  1.558
19     -999.000   88.767  115.058   15.337  2.879  15.337   58.211  0.875
20     -999.000   89.705   41.765   18.437  1.395  18.437   57.157  1.082
21       90.736   18.674   60.231   25.156  2.363  25.156   64.833  0.749
22       87.075   38.217   67.041    2.347  2.852   2.347   65.281  1.276
23      141.481    0.736  111.581  174.075  1.335   6.663  440.859  0.652
24      110.785   72.927   82.775   30.888  3.032  30.888   77.888  2.581
25       76.883   34.384   56.993    5.569  2.912   5.569   58.116  1.492
26      137.197   68.009   78.296   35.332  2.883   0.204  115.081  1.295
27      111.271   27.180   70.642  144.766  1.795   0.367  309.992  2.848
28      118.104    2.633   77.310   91.388  1.976  21.536  159.743  1.172
29       98.761   14.024   74.230  132.806  1.261  23.290  239.330  1.541
...         ...      ...      ...      ...    ...     ...      ...    ...
249970  158.674   80.380   75.571  100.432  2.617  56.972  209.604  0.624
249971 -999.000  173.688   91.969    7.112  2.077   7.112  123.652  3.403
249972  102.569   53.660   69.926   78.133  2.229  27.140  127.080  1.977
249973  103.483    6.101   63.502  128.948  1.460   5.947  214.496  0.631
249974  128.898    2.446   92.990   77.170  2.141  31.853  129.941  0.800
249975  140.352   15.046   84.924  108.693  1.967   3.841  200.516  0.864
249976  137.371    4.640   92.603  107.121  2.149   2.755  225.261  1.783
249977   96.952   85.701   87.170    4.503  2.459   4.503   93.706  1.606
249978   86.190   17.227   60.069   39.628  2.857  39.628   60.457  1.874
249979   92.645    2.855   66.797   50.654  2.282   3.483  124.306  1.664
249980  119.934   20.078   88.751   35.227  2.800  18.532  189.198  1.951
249981   87.390    0.299   40.546  244.825  0.760  30.181  347.795  0.728
249982  146.903   83.727  104.591   34.762  3.168  34.762   99.382  1.168
249983   80.388   67.071   58.603   26.696  2.501  26.696   53.208  1.440
249984  112.308   30.722   73.178   32.298  3.078  32.298   75.714  0.537
249985  126.151   29.023   95.258  152.684  1.504  24.642  327.502  2.163
249986  164.310    1.535  115.781    8.417  3.041   8.417  115.790  0.685
249987  140.080   29.729   83.393    7.918  2.673  38.975  133.039  0.370
249988   89.509   86.277   79.870   56.636  1.709  23.499  154.023  0.885
249989 -999.000   78.256   79.699  127.508  1.234  48.742  217.820  1.463
249990  127.822   82.865  100.024    0.860  3.210   0.860   71.325  2.322
249991  133.457   77.540   88.989   69.650  2.484   2.490  166.396  0.629
249992 -999.000   

We can see that there is a lot of incorrect -999 values. We therefore need to preprocess the data in order to extract on the good features. 

In [14]:
pd.DataFrame(np.delete(tX, 4, axis=1))

0        1        2        3         4        5      6       7   \
0       138.470   51.655   97.827   27.980   124.711    2.666  3.064  41.928   
1       160.937   68.768  103.235   48.146  -999.000 -999.000  3.473   2.078   
2      -999.000  162.172  125.953   35.635  -999.000 -999.000  3.148   9.336   
3       143.905   81.417   80.943    0.414  -999.000 -999.000  3.310   0.414   
4       175.864   16.915  134.805   16.405  -999.000 -999.000  3.891  16.405   
5        89.744   13.550   59.149  116.344   284.584   -0.540  1.362  61.619   
6       148.754   28.862  107.782  106.130   158.359    0.113  2.941   2.545   
7       154.916   10.418   94.714   29.169  -999.000 -999.000  2.897   1.526   
8       105.594   50.559  100.989    4.288  -999.000 -999.000  2.904   4.288   
9       128.053   88.941   69.272  193.392  -999.000 -999.000  1.609  28.859   
10     -999.000   86.240   79.692   27.201  -999.000 -999.000  2.338  27.201   
11      114.744   10.286   75.712   30.816   252.599   -1.401  2.888  36.745   
12      145.297   64.234  103.565  106.999  -999.000 -999.000  2.183  24.660   
13       82.488   31.663   64.128    8.232  -999.000 -999.000  2.823   8.232   
14     -999.000  109.412   14.398   17.323  -999.000 -999.000  0.472  17.323   
15      111.026   32.096   75.271   23.067  -999.000 -999.000  3.205  23.067   
16      114.256    4.351   67.963   47.221  -999.000 -999.000  2.954  26.243   
17      127.861   50.953   77.267   26.967  -999.000 -999.000  2.833  26.967   
18     -999.000   85.186   68.827    5.042  -999.000 -999.000  2.116   5.042   
19     -999.000   88.767  115.058   15.337  -999.000 -999.000  2.879  15.337   
20     -999.000   89.705   41.765   18.437  -999.000 -999.000  1.395  18.437   
21       90.736   18.674   60.231   25.156  -999.000 -999.000  2.363  25.156   
22       87.075   38.217   67.041    2.347  -999.000 -999.000  2.852   2.347   
23      141.481    0.736  111.581  174.075   364.344   -0.923  1.335   6.663   
24      110.785   72.927   82.775   30.888  -999.000 -999.000  3.032  30.888   
25       76.883   34.384   56.993    5.569  -999.000 -999.000  2.912   5.569   
26      137.197   68.009   78.296   35.332  -999.000 -999.000  2.883   0.204   
27      111.271   27.180   70.642  144.766  1021.322   -5.834  1.795   0.367   
28      118.104    2.633   77.310   91.388  -999.000 -999.000  1.976  21.536   
29       98.761   14.024   74.230  132.806   315.854   -2.665  1.261  23.290   
...         ...      ...      ...      ...       ...      ...    ...     ...   
249970  158.674   80.380   75.571  100.432   817.071   -6.275  2.617  56.972   
249971 -999.000  173.688   91.969    7.112  -999.000 -999.000  2.077   7.112   
249972  102.569   53.660   69.926   78.133  -999.000 -999.000  2.229  27.140   
249973  103.483    6.101   63.502  128.948  -999.000 -999.000  1.460   5.947   
249974  128.898    2.446   92.990   77.170  -999.000 -999.000  2.141  31.853   
249975  140.352   15.046   84.924  108.693  -999.000 -999.000  1.967   3.841   
249976  137.371    4.640   92.603  107.121   322.430   -2.384  2.149   2.755   
249977   96.952   85.701   87.170    4.503  -999.000 -999.000  2.459   4.503   
249978   86.190   17.227   60.069   39.628  -999.000 -999.000  2.857  39.628   
249979   92.645    2.855   66.797   50.654  -999.000 -999.000  2.282   3.483   
249980  119.934   20.078   88.751   35.227   111.491    1.836  2.800  18.532   
249981   87.390    0.299   40.546  244.825  -999.000 -999.000  0.760  30.181   
249982  146.903   83.727  104.591   34.762  -999.000 -999.000  3.168  34.762   
249983   80.388   67.071   58.603   26.696  -999.000 -999.000  2.501  26.696   
249984  112.308   30.722   73.178   32.298  -999.000 -999.000  3.078  32.298   
249985  126.151   29.023   95.258  152.684   163.066   -0.240  1.504  24.642   
249986  164.310    1.535  115.781    8.417  -999.000 -999.000  3.041   8.417   
249987  140.080   29.729   83.393    7.918  -999.000 -999.000  2.673  38.975   
249988   89.5

In [15]:
np.mean(tX, axis=0)

array([-4.90230794e+01,  4.92398193e+01,  8.11819816e+01,  5.78959617e+01,
       -7.08420675e+02, -6.01237051e+02, -7.09356603e+02,  2.37309984e+00,
        1.89173324e+01,  1.58432217e+02,  1.43760943e+00, -1.28304708e-01,
       -7.08985189e+02,  3.87074191e+01, -1.09730480e-02, -8.17107200e-03,
        4.66602072e+01, -1.95074680e-02,  4.35429640e-02,  4.17172345e+01,
       -1.01191920e-02,  2.09797178e+02,  9.79176000e-01, -3.48329567e+02,
       -3.99254314e+02, -3.99259788e+02, -6.92381204e+02, -7.09121609e+02,
       -7.09118631e+02,  7.30645914e+01])

In [ ]:
processedFeatures = np.where(tX==-999, 0, tX)

In [ ]:
np.mean(pd.DataFrame(processedFeatures), axis=0)

In [ ]:
plt.hist(tX[0])


In [ ]:
tX[0]

In [ ]:
plt.hist(tX[0])

In [4]:
from sklearn.metrics import confusion_matrix
y_true = [2, 0, 2, 2, 0, 1]
y_pred = [0, 0, 2, 2, 0, 2]
confusion_matrix(y_true, y_pred)    

array([[2, 0, 0],
       [0, 0, 1],
       [1, 0, 2]])

## Generate predictions and save ouput in csv format for submission:

In [ ]:
DATA_TEST_PATH = '' # TODO: download train data and supply path here 
_, tX_test, ids_test = load_csv_data(DATA_TEST_PATH)

In [ ]:
OUTPUT_PATH = '' # TODO: fill in desired name of output file for submission
y_pred = predict_labels(weights, tX_test)
create_csv_submission(ids_test, y_pred, OUTPUT_PATH)